### ISSUE TITLE
Error in line 90...

### ISSUE THREAD

**Issue by schroepfer** [kingkingyyk/Pi-MJPEG-Server#1]
Hello,
executing mjpeg_server.py gives an error:

SyntaxError: invalid syntax
File "/home/juergen/Pi-MJPEG-Server/mjpeg_server.py", line 90
    def down(self):
    ^

How can i fix this?

Regards
Juergen

**Comment by hibenji** [comment]
I get the same issue :/

**Comment by hibenji** [comment]
Hey @schroepfer,
Im not sure what the issue is, but i noticed that an older commit works 👍 
https://github.com/kingkingyyk/Pi-MJPEG-Server/tree/817f6e6b10825ff89ce972a5ec61d9f336006b82

I hope i could help :)

**Comment by schroepfer** [comment]
Hello,
this commit works!
Thank you!

**Comment by schroepfer** [comment]
The software is very unstable.
After some minutes i get this in the console:

_client_loop: send disconnect: Broken pipe_

and it stops working.

**Comment by hibenji** [comment]
It worked fine for me.
What camera and Pi are you using?
I used a Rapsberry Pi 4 and cam v3
There is also a diffrent MJPEG server while this gets fixed. (https://github.com/raspberrypi/picamera2/blob/main/examples/mjpeg_server.py)

It has some less features (not AF, no HDR), but it works.

**Comment by schroepfer** [comment]
I use a cam V3 on a Pi Zero 2.

I don't wont this other server because of no AF...

**Comment by kingkingyyk** [comment]
@schroepfer Hi, I've fixed the typo in the latest commit, see if it works for you? ;)

As for the stability issue, do you have info like stdout and stderr to provide? If you can launch it as service, you can use `sudo systemctl status <servicename>` to get them. Otherwise you will need to do file redirection `command &> file`.

**Comment by schroepfer** [comment]
Thanks!
It runs now since 24 hours stable!
...and 48h...

**Comment by kingkingyyk** [comment]
Since no more additional information, I assume it is fixed.
